### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by leouieda** [fatiando-data/southern-africa-topography#2]
Checklist:

- [x] Reserve a DOI on Zenodo and save the entry (fill required information first).
- [x] Update the DOI in the README
- [x] Update the release number, file size, and checksums in the README
- [x] Update the list of changes in the README
- [x] Fill out the Zenodo metadata and description following the example other Fatiando Data publications and latest changes from the README
- [x] Create a new release (use the template below). The release name should be the version number with a leading `v` (e.g. `v1`).
- [x] Upload the new data file to the release
- [x] Publish the release
- [x] Upload the new data file to Zenodo
- [x] Publish the Zenodo archive

GitHub release template:

```markdown
**Date:** YYYY/MM/DD

**DOI:** https://doi.org/XXXX

**Note:** This is a processed and formatted version of the source dataset below. It's mean for use in documentation and tutorials of the Fatiando a Terra project. Please cite the original authors when using this dataset.

**Data source:** [The reference](Link to the reference, preferably a DOI)

**Changes:**

* List of changes made to the data 

| | Checksums |
|--:|:--|
| MD5 | `md5:XXX` |
| SHA256 | `sha256:XXX` |
```

**Comment by leouieda** [comment]
@santisoler made a little checklist here of things to do for a release. See if it works and then we can add it as a template in this org.

**Comment by santisoler** [comment]
Done! Thanks for the checklist! They always come very handy. I made some edits to the checklist based on the experience.
For instance, in order to reserve a DOI we need to fill the required fields (title, publication date, authors, description), otherwise the Save button is greyed out.

**Comment by leouieda** [comment]
Awesome! Glad it was useful and thanks for the feedback!
